export const TOKEN_INVALID =  'TOKEN_INVALID';
export const INVALID_COUNTRY = 'INVALID_COUNTRY';
export const INVALID_PARAMETERS = 'INVALID_PARAMETERS';
export const INVALID_GITHUB_ACCOUNT_AGE = 'INVALID_GITHUB_ACCOUNT_AGE';
export const INVALID_REQ_WITHIN_DELAY_PERIOD = 'INVALID_REQ_WITHIN_DELAY_PERIOD';
export const INVALID_USER_COUNTRY = 'INVALID_USER_COUNTRY';
export const INVALID_CHAIN_ADDRESS = 'INVALID_CHAIN_ADDRESS';
export const INVALID_TOC_PRIVACY = 'INVALID_TOC_PRIVACY';
